name = input('Name? ')
print(name * 3 + '...')
print('What are we gonna do with you.')
print('Nice ' + str(len(name)) + ' character name you got there.')
age = int(input('Age? '))
print('Wow, that\'s ' + str(age // 10) + ' decades!')
print('(Give or take ' + str(age % 10) + ' years.)')
print('Imagine.. Just 3 short years ago, you were ' + str(age - 3) + '.')
print('But don\'t worry. Give it another 3 and you\'ll be ' + str(age + 3) + ' in no time.')
print('Half a lifetime ago, you were ' + str(round(age / 2)) + ' years old.')
print('Double your entire life so far and that\'ll put you at ' + str(age * 2) + '.. Gosh.')
print('By the way, ' + str(age) + ' squared is ' + str(age ** 2) + '. Just so you know.')
# floating point number, concatenate
month = float(input('Months until your birthday? '))
year = round(month / 12.0, 3)
print('That\'s a mere ' + str(year) + ' years away! Get hyped!')
